convert	public/assets/models/characters/avatar/texture/f_1_cloth_1.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_1_cloth_1.jpg
convert	public/assets/models/characters/avatar/texture/f_1_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_1_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_10_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_10_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_11_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_11_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_12_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_12_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_2_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_2_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_3_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_3_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_4_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_4_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_5_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_5_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_6_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_6_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_7_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_7_cloth.jpg
convert	public/assets/models/characters/avatar/texture/f_9_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/f_9_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_1_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_1_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_10_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_10_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_11_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_11_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_12_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_12_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_13_cloth_1.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_13_cloth_1.jpg
convert	public/assets/models/characters/avatar/texture/m_13_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_13_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_2_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_2_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_3_cloth_1.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_3_cloth_1.jpg
convert	public/assets/models/characters/avatar/texture/m_3_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_3_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_4_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_4_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_5_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_5_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_6_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_6_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_7_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_7_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_8_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_8_cloth.jpg
convert	public/assets/models/characters/avatar/texture/m_9_cloth.jpg	-resize 256X256!	public/assets/draco/characters/avatar/texture/m_9_cloth.jpg

yarn gltf-transform draco public/assets/models/landscape/landscape.glb public/assets/draco/landscape/landscape.glb
yarn gltf-transform draco public/assets/models/characters/avatar/f_1.gltf public/assets/draco/characters/avatar/f_1.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_2.gltf public/assets/draco/characters/avatar/f_2.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_3.gltf public/assets/draco/characters/avatar/f_3.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_4.gltf public/assets/draco/characters/avatar/f_4.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_5.gltf public/assets/draco/characters/avatar/f_5.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_6.gltf public/assets/draco/characters/avatar/f_6.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_7.gltf public/assets/draco/characters/avatar/f_7.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_8.gltf public/assets/draco/characters/avatar/f_8.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_9.gltf public/assets/draco/characters/avatar/f_9.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_10.gltf public/assets/draco/characters/avatar/f_10.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_11.gltf public/assets/draco/characters/avatar/f_11.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/f_12.gltf public/assets/draco/characters/avatar/f_12.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_1.gltf public/assets/draco/characters/avatar/m_1.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_2.gltf public/assets/draco/characters/avatar/m_2.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_3.gltf public/assets/draco/characters/avatar/m_3.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_4.gltf public/assets/draco/characters/avatar/m_4.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_5.gltf public/assets/draco/characters/avatar/m_5.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_6.gltf public/assets/draco/characters/avatar/m_6.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_7.gltf public/assets/draco/characters/avatar/m_7.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_8.gltf public/assets/draco/characters/avatar/m_8.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_9.gltf public/assets/draco/characters/avatar/m_9.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_10.gltf public/assets/draco/characters/avatar/m_10.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_11.gltf public/assets/draco/characters/avatar/m_11.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_12.gltf public/assets/draco/characters/avatar/m_12.gltf
yarn gltf-transform draco public/assets/models/characters/avatar/m_13.gltf public/assets/draco/characters/avatar/m_13.gltf
yarn gltf-transform draco public/assets/models/status/chess.glb public/assets/draco/status/chess.glb
yarn gltf-transform draco public/assets/models/status/ludo.glb public/assets/draco/status/ludo.glb